@BudgetApp_HostAddress = http://localhost:5158

POST {{BudgetApp_HostAddress}}/transaction
Content-Type: application/json

{
    "amount": 25.50,
    "date": "2026-03-18",
    "category": "Food"
}

###

GET {{BudgetApp_HostAddress}}/transactions
Accept: application/json

###